# NumPy Review Notebook

In [1]:
import numpy as np

In [2]:
# making a numpy array

np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Built-in methods

In [5]:
np.arange(0,10)  # exclusivs end point

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [10]:
# Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

In [11]:
# To Create a Random array with Uniform Dis. between [0, 1) use `RANDOM.RAND`

np.random.rand(3,4)

array([[0.9892425 , 0.61229688, 0.58199132, 0.87914729],
       [0.62622493, 0.70142937, 0.41589391, 0.54176535],
       [0.1117093 , 0.46848802, 0.45015678, 0.50118584]])

In [12]:
np.random.rand(5)

array([0.09490065, 0.36535571, 0.51398352, 0.666929  , 0.77607567])

In [13]:
# To return Standard Normal Dis. with sigma=1, use `Random.RANDN`

np.random.randn(3,4)

array([[ 1.22880995,  1.02046166,  0.58369261,  0.13218333],
       [ 0.07222435,  0.10000577,  0.46699573,  1.71170457],
       [ 0.81561901,  0.24086607,  1.16393277, -0.39482358]])

In [14]:
# Return random integers between two given numbers [low, high), use `Random.RANDINT`

np.random.randint(0,100, (5,2))

array([[50, 90],
       [57, 49],
       [97, 59],
       [28, 41],
       [78, 48]])

In [15]:
# use seed to generate the same random numbers
np.random.seed(1)
np.random.randn(5)

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763])

In [16]:
# Reshape
arr = np.arange(1,21)
arr.reshape((5,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [17]:
# max, argmax, min, argmin
arr = np.random.randint(0,100, (5,5))

In [18]:
arr

array([[18, 84, 11, 28, 29],
       [14, 50, 68, 87, 87],
       [94, 96, 86, 13,  9],
       [ 7, 63, 61, 22, 57],
       [ 1,  0, 60, 81,  8]])

In [19]:
arr.max()

96

In [20]:
arr.argmax()

11

In [21]:
arr.min()

0

In [22]:
# Shape

arr.shape

(5, 5)

In [23]:
# Data type == dtype

arr.dtype

dtype('int32')

In [24]:
np.linspace(0,25).dtype

dtype('float64')

# Indexing

<img src= 'numpy_indexing.png' width=500/>

In [25]:
arr

array([[18, 84, 11, 28, 29],
       [14, 50, 68, 87, 87],
       [94, 96, 86, 13,  9],
       [ 7, 63, 61, 22, 57],
       [ 1,  0, 60, 81,  8]])

In [26]:
arr[0:2,0:2]

array([[18, 84],
       [14, 50]])

In [27]:
arr[1,4]

87

**Important Note on Slicing**   
When we slice an array, every changes also occur on the original array

In [28]:
s = arr[4]
s

array([ 1,  0, 60, 81,  8])

In [29]:
s[:] = np.zeros(5)

In [30]:
print(f"slice of arr {s} \n")
print("array itself changes to :")
print(arr)

slice of arr [0 0 0 0 0] 

array itself changes to :
[[18 84 11 28 29]
 [14 50 68 87 87]
 [94 96 86 13  9]
 [ 7 63 61 22 57]
 [ 0  0  0  0  0]]


## Conditional Selection
This is a very fundamental concept that will directly translate to pandas later on

In [31]:
arr

array([[18, 84, 11, 28, 29],
       [14, 50, 68, 87, 87],
       [94, 96, 86, 13,  9],
       [ 7, 63, 61, 22, 57],
       [ 0,  0,  0,  0,  0]])

In [32]:
arr[arr >= 50]

array([84, 50, 68, 87, 87, 94, 96, 86, 63, 61, 57])

# NumPy Operations

In [33]:
# SUM

arr + arr

array([[ 36, 168,  22,  56,  58],
       [ 28, 100, 136, 174, 174],
       [188, 192, 172,  26,  18],
       [ 14, 126, 122,  44, 114],
       [  0,   0,   0,   0,   0]])

In [34]:
# Multiplication

arr * arr # or arr ** 2

array([[ 324, 7056,  121,  784,  841],
       [ 196, 2500, 4624, 7569, 7569],
       [8836, 9216, 7396,  169,   81],
       [  49, 3969, 3721,  484, 3249],
       [   0,    0,    0,    0,    0]])

In [35]:
# It raise error because of dividing by zero, but it will take of that too with `nan`
arr / arr

C:\Users\rafes\AppData\Local\Temp/ipykernel_10460/2485474980.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [nan, nan, nan, nan, nan]])

In [36]:
1 / arr

C:\Users\rafes\AppData\Local\Temp/ipykernel_10460/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([[0.05555556, 0.01190476, 0.09090909, 0.03571429, 0.03448276],
       [0.07142857, 0.02      , 0.01470588, 0.01149425, 0.01149425],
       [0.0106383 , 0.01041667, 0.01162791, 0.07692308, 0.11111111],
       [0.14285714, 0.01587302, 0.01639344, 0.04545455, 0.01754386],
       [       inf,        inf,        inf,        inf,        inf]])

## Universal Array Functions

exp, sin, sqrt, cos, log, ... these come with `np.ufunc(arr)`   
mean, sum, std, var, ... these comes both ways `np.ufunc(arr)` or `arr.ufunc()`

In [37]:
np.mean(arr)       # also arr.mean()

39.36

In [38]:
np.sum(arr)        # also arr.sum()

984

In [39]:
np.exp(arr)

array([[6.56599691e+07, 3.02507732e+36, 5.98741417e+04, 1.44625706e+12,
        3.93133430e+12],
       [1.20260428e+06, 5.18470553e+21, 3.40427605e+29, 6.07603023e+37,
        6.07603023e+37],
       [6.66317622e+40, 4.92345829e+41, 2.23524660e+37, 4.42413392e+05,
        8.10308393e+03],
       [1.09663316e+03, 2.29378316e+27, 3.10429794e+26, 3.58491285e+09,
        5.68572000e+24],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00]])

In [40]:
np.var(arr)       # also arr.var()

1200.9504

In [41]:
np.sum(arr, axis=1)     # axis=1 means horizontally, axis=0 means vertically

array([170, 306, 298, 210,   0])

In [42]:
arr.sum(axis=0)

array([133, 293, 226, 150, 182])